export const USER_SIGNIN_API = 'USER_SIGNIN_API'


//login

export const USLOGIN = 'USLOGIN';

//get project

export const GET_PROJECT_CATEGORY_SAGA = 'GET_PROJECT_CATEGORY_SAGA'


export const GET_PROJECT_CATEGORY = 'GET_PROJECT_CATEGORY'

export const CREATE_PROJECT_CATEGORY_SAGA = 'CREATE_PROJECT_CATEGORY_SAGA'

export const GET_LIST_PROJECT_SAGA = 'GET_LIST_PROJECT_SAGA'


export const GET_LIST_PROJECT = 'GET_LIST_PROJECT'

export const UPDATE_PROJECT = 'UP_DATE_PROJECT'

export const UP_DATE_PROJECT_SAGA = 'UP_DATE_PROJECT_SAGA'

export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA'

export const GET_USER_SAGA = 'GET_USER_SAGA'

export const GET_USER = 'GET_USER'

export const ADD_USER_PROJECT_SAGA = 'ADD_USER_PROJECT_SAGA'

export const REMOVE_USER_FROM_PROJECT_SAGA = 'REMOVE_USER_FROM_PROJECT_SAGA'


export const GET_PROJECT_DETAIL_SAGA = "GET_PROJECT_DETAIL_SAGA"

export const PUT_PROJECT_DETAIL ='PUT_PROJECT_DETAIL'


export const GET_TASK_TYPE_SAGA ='GET_TASK_TYPE_SAGA'

export const GET_TASK_TYPE ='GET_TASK_TYPE'


export const GET_PRIORITY = 'GET_PRIORITY'

export const GET_PRIORITY_SAGA = 'GET_PRIORITY_SAGA'

export const GET_STATUS_ALL_SAGA = 'GET_STATUS_ALL_SAGA'

export const GET_STATUS_ALL = 'GET_STATUS_ALL'

export const GET_USER_BY_PROJECT_ID_SAGA = 'GET_USER_BY_PROJECT_ID_SAGA'

export const GET_USER_BY_PROJECT_ID = 'GET_USER_BY_PROJECT_ID'


export const CREATE_TASK_SAGA = "CREATE_TASK_SAGA"


export const TASK_DETAIL_MODAIL = 'TASK_DETAIL_MODAIL'

export const UPDATE_STATUS_TASK_SAGA = 'UPDATE_STATUS_TASK_SAGA'

export const GET_TASK_DETAIL_SAGA ='GET_TASK_DETAIL_SAGA'

export const TASK_DETAIL_MODAIL_SAGA ='TASK_DETAIL_MODAIL_SAGA'

export const CHANGE_TASK_MODAL = 'CHANGE_TASK_MODAL'
export const CHANGE_ASSIGNESS = 'CHANGE_ASSIGNESS'

export const REMOVE_USER_TASK ="REMOVE_USER_TASK"

export const HANDLE_CHANGE_TASK_POST_API_SAGA = 'HANDLE_CHANGE_TASK_POST_API_SAGA'