export const CREATE_PROJECT_SAGA ="CREATE_PROJECT_SAGA"

export const GET_ALL_PROJECT_SAGA = 'GET_ALL_PROJECT_SAGA'

export const GET_ALL_PROJECT = 'GET_ALL_PROJECT'

export const UP_DATE_PROJECT_SAGA ='UP_DATE_PROJECT_SAGA'

export const DELETE_PROJECT_SAGA ="DELETE_PROJECT_SAGA"

export const ASSIGN_USER_TASK_SAGA ='ASSIGN_USER_TASK_SAGA'

export const REMOVE_USER_FROM_PROJECT ='REMOVE_USER_FROM_PROJECT'

export const GET_PROJECT_DETAIL_SAGA = "GET_PROJECT_DETAIL_SAGA"